import type { Property, Branding } from '../types/property';

export const branding: Branding = {
  name: 'ScanHouse',
  tagline: 'UNA PROPIEDAD NO SE MUESTRA. SE EXPERIMENTA.',
  logo: '',
  primaryColor: '#ffffff',
  secondaryColor: '#a3a3a3',
};

export const property: Property = {
  id: 'casa-laureles',
  name: 'CASA LAURELES',
  location: 'San Salvador de Jujuy, Argentina',
  price: 145000,
  currency: 'USD',
  bedrooms: 3,
  bathrooms: 2,
  coveredArea: 180,
  landArea: 420,
  garages: 2,
  features: [
    'Jardín',
    'Cocina integrada',
    'Living/Comedor',
    'Patio',
    'Dormitorio principal',
    'Baño privado',
    '2 cocheras',
  ],
  description:
    'Casa Laureles es una propiedad premium que combina arquitectura contemporánea con calidez residencial. Sus amplios espacios integrados, materiales nobles y distribución inteligente crean una experiencia de vida única en una de las zonas más cotizadas de San Salvador de Jujuy.',
  images: [],
  scenes: [
    {
      id: 'salon',
      name: 'SALÓN',
      panorama: '/panoramas/salon.jpg',
      thumbnail: '/thumbnails/salon.jpg',
      description:
        'Amplio living-comedor con doble altura, ventanales de piso a techo que inundan el espacio de luz natural y pisos de porcelanato de gran formato. La conexión visual con el jardín y el patio trasero crea una sensación de continuidad entre interior y exterior.',
      position: { x: 0, y: 0, z: 0 },
      rotation: { yaw: 0, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'salon-cocina',
          type: 'navigation',
          name: 'COCINA',
          pitch: 0,
          yaw: 90,
          targetSceneId: 'cocina',
        },
        {
          id: 'salon-pasillo',
          type: 'navigation',
          name: 'PASILLO',
          pitch: 0,
          yaw: -90,
          targetSceneId: 'pasillo',
        },
        {
          id: 'salon-patio',
          type: 'navigation',
          name: 'PATIO',
          pitch: 10,
          yaw: 180,
          targetSceneId: 'patio',
        },
        {
          id: 'salon-info-chimenea',
          type: 'info',
          name: 'CHIMENEA',
          pitch: -10,
          yaw: 45,
          content: 'Chimenea de bioetanol de diseño italiano. Funciona sin salida de humos, genera calor real y es ecológica.',
        },
        {
          id: 'salon-info-ventanales',
          type: 'info',
          name: 'VENTANALES',
          pitch: -15,
          yaw: -45,
          content: 'Ventanales DVH (doble vidriado hermético) con control solar. Aislamiento térmico y acústico superior.',
        },
      ],
      connections: [
        { targetSceneId: 'cocina', hotspotId: 'salon-cocina' },
        { targetSceneId: 'pasillo', hotspotId: 'salon-pasillo' },
        { targetSceneId: 'patio', hotspotId: 'salon-patio' },
      ],
    },
    {
      id: 'cocina',
      name: 'COCINA',
      panorama: '/panoramas/cocina.jpg',
      thumbnail: '/thumbnails/cocina.jpg',
      description:
        'Cocina integrada de diseño minimalista con mesada de granito negro, muebles bajo mesada y alacenas en laca mate. Equipada con anafe eléctrico de 4 hornallas, horno empotrado y espacio preparado para lavavajillas. Isla central con barra desayunadora.',
      position: { x: 4, y: 0, z: 0 },
      rotation: { yaw: 90, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'cocina-salon',
          type: 'navigation',
          name: 'SALÓN',
          pitch: 0,
          yaw: -90,
          targetSceneId: 'salon',
        },
        {
          id: 'cocina-pasillo',
          type: 'navigation',
          name: 'PASILLO',
          pitch: 0,
          yaw: 180,
          targetSceneId: 'pasillo',
        },
        {
          id: 'cocina-info-mesada',
          type: 'info',
          name: 'MESADA',
          pitch: 5,
          yaw: 30,
          content: 'Mesada de granito Negro Brasil de 3cm de espesor. Resistente a calor, manchas y rayones. Incluye bacha de acero inoxidable integrada.',
        },
        {
          id: 'cocina-info-anafe',
          type: 'info',
          name: 'ANAFE',
          pitch: -5,
          yaw: -30,
          content: 'Anafe vitrocerámico de 4 zonas de cocción con control táctil, timer y bloqueo de seguridad para niños.',
        },
      ],
      connections: [
        { targetSceneId: 'salon', hotspotId: 'cocina-salon' },
        { targetSceneId: 'pasillo', hotspotId: 'cocina-pasillo' },
      ],
    },
    {
      id: 'pasillo',
      name: 'PASILLO',
      panorama: '/panoramas/pasillo.jpg',
      thumbnail: '/thumbnails/pasillo.jpg',
      description:
        'Distribuidor principal que conecta la zona social con la zona privada. Placares de guardado empotrados con puertas espejo que amplían visualmente el espacio. Iluminación indirecta LED en zócalos y techo.',
      position: { x: 0, y: 4, z: 0 },
      rotation: { yaw: 180, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'pasillo-salon',
          type: 'navigation',
          name: 'SALÓN',
          pitch: 0,
          yaw: 90,
          targetSceneId: 'salon',
        },
        {
          id: 'pasillo-cocina',
          type: 'navigation',
          name: 'COCINA',
          pitch: 0,
          yaw: -90,
          targetSceneId: 'cocina',
        },
        {
          id: 'pasillo-dormitorio1',
          type: 'navigation',
          name: 'DORMITORIO PRINCIPAL',
          pitch: 0,
          yaw: 0,
          targetSceneId: 'dormitorio-principal',
        },
        {
          id: 'pasillo-dormitorio2',
          type: 'navigation',
          name: 'DORMITORIO 2',
          pitch: 0,
          yaw: 180,
          targetSceneId: 'dormitorio-2',
        },
        {
          id: 'pasillo-bano',
          type: 'navigation',
          name: 'BAÑO',
          pitch: 0,
          yaw: -45,
          targetSceneId: 'bano',
        },
      ],
      connections: [
        { targetSceneId: 'salon', hotspotId: 'pasillo-salon' },
        { targetSceneId: 'cocina', hotspotId: 'pasillo-cocina' },
        { targetSceneId: 'dormitorio-principal', hotspotId: 'pasillo-dormitorio1' },
        { targetSceneId: 'dormitorio-2', hotspotId: 'pasillo-dormitorio2' },
        { targetSceneId: 'bano', hotspotId: 'pasillo-bano' },
      ],
    },
    {
      id: 'dormitorio-principal',
      name: 'DORMITORIO PRINCIPAL',
      panorama: '/panoramas/dormitorio-principal.jpg',
      thumbnail: '/thumbnails/dormitorio-principal.jpg',
      description:
        'Suite principal con salida directa al jardín. Vestidor completo con iluminación interior automatizada. Ventanales con blackout motorizado. Piso de madera de roble europeo. Baño en suite con doble bacha, ducha con mampara de vidrio fijo y bañera exenta.',
      position: { x: -4, y: 4, z: 0 },
      rotation: { yaw: -90, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'dorm1-pasillo',
          type: 'navigation',
          name: 'PASILLO',
          pitch: 0,
          yaw: 180,
          targetSceneId: 'pasillo',
        },
        {
          id: 'dorm1-bano',
          type: 'navigation',
          name: 'BAÑO EN SUITE',
          pitch: 0,
          yaw: -90,
          targetSceneId: 'bano',
        },
        {
          id: 'dorm1-info-vestidor',
          type: 'info',
          name: 'VESTIDOR',
          pitch: -10,
          yaw: 45,
          content: 'Vestidor de 4m² con sistema de organización modular: barras, cajoneras, estantes y zapatera. Iluminación LED con sensor de presencia.',
        },
        {
          id: 'dorm1-info-ventanas',
          type: 'info',
          name: 'BLACKOUT MOTORIZADO',
          pitch: -15,
          yaw: -45,
          content: 'Cortinas blackout motorizadas con control remoto e integración domótica. Programables por horarios.',
        },
      ],
      connections: [
        { targetSceneId: 'pasillo', hotspotId: 'dorm1-pasillo' },
        { targetSceneId: 'bano', hotspotId: 'dorm1-bano' },
      ],
    },
    {
      id: 'dormitorio-2',
      name: 'DORMITORIO 2',
      panorama: '/panoramas/dormitorio-2.jpg',
      thumbnail: '/thumbnails/dormitorio-2.jpg',
      description:
        'Segundo dormitorio con placard completo de piso a techo con interiores organizados. Ventana con vista al jardín lateral. Piso de madera de roble europeo. Preparado para Split de aire acondicionado.',
      position: { x: 4, y: 4, z: 0 },
      rotation: { yaw: 90, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'dorm2-pasillo',
          type: 'navigation',
          name: 'PASILLO',
          pitch: 0,
          yaw: 0,
          targetSceneId: 'pasillo',
        },
        {
          id: 'dorm2-info-placard',
          type: 'info',
          name: 'PLACARD',
          pitch: 5,
          yaw: 30,
          content: 'Placard de 2.5m de ancho x 2.4m de alto. Interior: barra de colgar, 6 estantes, 3 cajones y zapatera.',
        },
      ],
      connections: [
        { targetSceneId: 'pasillo', hotspotId: 'dorm2-pasillo' },
      ],
    },
    {
      id: 'bano',
      name: 'BAÑO',
      panorama: '/panoramas/bano.jpg',
      thumbnail: '/thumbnails/bano.jpg',
      description:
        'Baño principal con doble bacha sobre mesada de mármol, grifería monocomando de diseño, ducha con mampara de vidrio templado 10mm y bañera exenta. Revestimientos en porcelanato de gran formato. Toallero eléctrico.',
      position: { x: 0, y: 6, z: 0 },
      rotation: { yaw: 0, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'bano-pasillo',
          type: 'navigation',
          name: 'PASILLO',
          pitch: 0,
          yaw: 180,
          targetSceneId: 'pasillo',
        },
        {
          id: 'bano-dorm1',
          type: 'navigation',
          name: 'DORMITORIO PRINCIPAL',
          pitch: 0,
          yaw: 90,
          targetSceneId: 'dormitorio-principal',
        },
        {
          id: 'bano-info-ducha',
          type: 'info',
          name: 'DUCHA',
          pitch: 0,
          yaw: -45,
          content: 'Ducha con columna de hidromasaje, rociador tipo lluvia y ducha telefónica. Mampara de vidrio templado 10mm con tratamiento anti-cal.',
        },
      ],
      connections: [
        { targetSceneId: 'pasillo', hotspotId: 'bano-pasillo' },
        { targetSceneId: 'dormitorio-principal', hotspotId: 'bano-dorm1' },
      ],
    },
    {
      id: 'patio',
      name: 'PATIO',
      panorama: '/panoramas/patio.jpg',
      thumbnail: '/thumbnails/patio.jpg',
      description:
        'Patio trasero con deck de madera ipé, pérgola bioclimática de aluminio con lamas orientables motorizadas, parrilla de acero inoxidable con campana, y jardineras con sistema de riego por goteo automatizado. Iluminación paisajística LED.',
      position: { x: 0, y: -4, z: 0 },
      rotation: { yaw: 180, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'patio-salon',
          type: 'navigation',
          name: 'SALÓN',
          pitch: -10,
          yaw: 0,
          targetSceneId: 'salon',
        },
        {
          id: 'patio-cochera',
          type: 'navigation',
          name: 'COCHERA',
          pitch: 0,
          yaw: 90,
          targetSceneId: 'cochera',
        },
        {
          id: 'patio-info-pergola',
          type: 'info',
          name: 'PÉRGOLA BIOCLIMÁTICA',
          pitch: -15,
          yaw: -30,
          content: 'Pérgola de aluminio con lamas orientables 0-140°. Sensor de lluvia para cierre automático. Iluminación LED perimetral regulable.',
        },
        {
          id: 'patio-info-parrilla',
          type: 'info',
          name: 'PARRILLA',
          pitch: 5,
          yaw: 30,
          content: 'Parrilla de acero inoxidable 304 con campana extraíble, brasero regulable y estantes laterales. Incluye set de herramientas.',
        },
      ],
      connections: [
        { targetSceneId: 'salon', hotspotId: 'patio-salon' },
        { targetSceneId: 'cochera', hotspotId: 'patio-cochera' },
      ],
    },
    {
      id: 'cochera',
      name: 'COCHERA',
      panorama: '/panoramas/cochera.jpg',
      thumbnail: '/thumbnails/cochera.jpg',
      description:
        'Cochera doble cubierta con portón automatizado, piso de hormigón pulido, instalación para carga de vehículo eléctrico, y espacio de guardado superior. Acceso directo al patio y entrada de servicio.',
      position: { x: 4, y: -4, z: 0 },
      rotation: { yaw: -90, pitch: 0, hfov: 100 },
      hotspots: [
        {
          id: 'cochera-patio',
          type: 'navigation',
          name: 'PATIO',
          pitch: 0,
          yaw: -90,
          targetSceneId: 'patio',
        },
        {
          id: 'cochera-info-cargador',
          type: 'info',
          name: 'CARGA VEHÍCULO ELÉCTRICO',
          pitch: 0,
          yaw: 0,
          content: 'Wallbox 22kW trifásico con conector Tipo 2. Gestión de carga inteligente via app. Compatible con todos los vehículos.',
        },
      ],
      connections: [
        { targetSceneId: 'patio', hotspotId: 'cochera-patio' },
      ],
    },
  ],
  floorPlan: {
    image: '/floorplan/casa-laureles.svg',
    rooms: [
      { id: 'patio', name: 'Patio', sceneId: 'patio', x: 8, y: 2, width: 52, height: 24 },
      { id: 'cochera', name: 'Cochera', sceneId: 'cochera', x: 66, y: 2, width: 28, height: 24 },
      { id: 'cocina', name: 'Cocina', sceneId: 'cocina', x: 8, y: 32, width: 26, height: 24 },
      { id: 'salon', name: 'Salón', sceneId: 'salon', x: 38, y: 32, width: 56, height: 26 },
      { id: 'pasillo', name: 'Pasillo', sceneId: 'pasillo', x: 22, y: 62, width: 14, height: 34 },
      { id: 'dormitorio-principal', name: 'Dorm. Principal', sceneId: 'dormitorio-principal', x: 42, y: 62, width: 28, height: 34 },
      { id: 'dormitorio-2', name: 'Dorm. 2', sceneId: 'dormitorio-2', x: 74, y: 62, width: 22, height: 34 },
      { id: 'bano', name: 'Baño', sceneId: 'bano', x: 2, y: 62, width: 16, height: 20 },
    ],
  },
  assistantKnowledge: {
    propertyDescription:
      'Casa Laureles es una propiedad premium de 180m² cubiertos sobre terreno de 420m² en San Salvador de Jujuy. Cuenta con 3 dormitorios, 2 baños, living-comedor integrado, cocina, patio con parrilla, pérgola bioclimática y cochera doble con cargador para auto eléctrico.',
    features: [
      '3 dormitorios (principal en suite con vestidor)',
      '2 baños completos (uno en suite)',
      'Living-comedor con doble altura',
      'Cocina integrada con isla y barra',
      'Patio con deck ipé y pérgola bioclimática',
      'Parrilla de acero inoxidable',
      'Cochera doble con cargador EV 22kW',
      'Pisos de porcelanato y roble europeo',
      'Calefacción por losa radiante',
      'Aire acondicionado Split en todos los ambientes',
      'Domótica: iluminación, cortinas, riego, seguridad',
      'DVH en todos los ventanales',
      'Blackout motorizado en dormitorios',
      'Riego por goteo automatizado',
      'Iluminación paisajística LED',
    ],
    price: 'USD 145.000',
    location: 'San Salvador de Jujuy, Argentina. Barrio residencial consolidado, a 5 min del centro comercial, 10 min del aeropuerto. Excelente conectividad.',
    rules: [
      'Se aceptan mascotas (consultar condiciones)',
      'No se permite fumar en interiores',
      'Visitas coordinadas con 24hs de antelación',
      'Contrato mínimo 2 años (alquiler) / Escritura inmediata (venta)',
    ],
    services: [
      'Agua corriente',
      'Gas natural',
      'Electricidad trifásica',
      'Internet fibra óptica',
      'Recolección de residuos',
      'Seguridad privada en el barrio',
    ],
    faq: [
      { question: '¿Cuántos dormitorios tiene?', answer: 'Tiene 3 dormitorios. El principal en suite con vestidor y baño privado, y dos dormitorios adicionales con placares completos.' },
      { question: '¿Tiene cochera?', answer: 'Sí, cochera doble cubierta con portón automatizado e instalación para carga de vehículo eléctrico (Wallbox 22kW).' },
      { question: '¿Cuánto cuesta?', answer: 'USD 145.000 (precio de venta). Para alquiler consultar condiciones.' },
      { question: '¿Tiene patio?', answer: 'Sí, patio trasero de aprox. 120m² con deck de madera ipé, pérgola bioclimática motorizada, parrilla y jardineras con riego automatizado.' },
      { question: '¿Acepta mascotas?', answer: 'Se aceptan mascotas bajo condiciones a convenir (tamaño, raza, cantidad). Consultar con la inmobiliaria.' },
      { question: '¿Dónde está ubicada?', answer: 'San Salvador de Jujuy, Argentina. Barrio residencial consolidado, a 5 min del centro comercial y 10 min del aeropuerto.' },
      { question: '¿Cuántos metros cuadrados tiene?', answer: '180m² cubiertos y 420m² de terreno total.' },
      { question: '¿Tiene baño privado?', answer: 'El dormitorio principal tiene baño en suite privado con doble bacha, ducha y bañera exenta. Hay un segundo baño completo para el resto de la casa.' },
      { question: '¿Puedo visitarla?', answer: 'Sí, las visitas se coordinan con 24hs de antelación. Complete el formulario "SOLICITAR VISITA" o contacte por WhatsApp.' },
    ],
    contact: {
      whatsapp: '+54 9 388 123 4567',
      email: 'contacto@inmobiliaria.com',
      phone: '+54 388 123 4567',
      agency: 'Inmobiliaria Premium Jujuy',
    },
  },
  branding,
};